### ISSUE TITLE
Not working for some reason :( 

### ISSUE THREAD

**Issue by koleror** [pitomba/spriter#28]
Hi,
I just finished implementing your library but for some reason I can't get the images to work...
When I add the right class to a span, it matches with the right css class the the image doesn't show up.
When I look at the css, I'm a bit surprised because you do not specify any image height or width. Only a position is set. How can the browser know what size the image is?
Here is what I put in the HTML:

``` html
<span class="mytag sreceipt"></span>
```

This is the matching css:

``` css
.mytag.sreceipt {
background-position: -6358px 0px;
}
.mytag {
background: url("../images/sprite/sprite.png");
}
```

I checked and the sprite is loaded properly (no 404).

Please answer asap or I'll have to use another library :( 

Thanks!

**Comment by koleror** [comment]
To make it work, I need to add this:

``` css
.mytag.sreceipt {
background-position: -6358px 0px;
width: 138px;
height: 188px;
}
.mytag {
background: url("../images/sprite/sprite.png");
display: inline-block;
}
```
